// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JavaScriptPrettier
{
    static class Vsix
    {
        public const string Id = "J1da7ad9e-85b3-4a0c-8e45-b2ae59a575a7";
        public const string Name = "JavaScript Prettier";
        public const string Description = @"Prettier is an opinionated JavaScript formatter inspired by refmt with advanced support for language features from ES2017, JSX, and Flow. It removes all original styling and ensures that all outputted JavaScript conforms to a consistent style.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "JavaScript, JSX, EcmaScript, formatting";
    }
}
