// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JavaScriptPrettier
{
    static class Vsix
    {
        public const string Id = "J1da7ad9e-85b3-4a0c-8e45-b2ae59a575a7";
        public const string Name = "JavaScript Prettier";
        public const string Description = @"Formats JavaScript and JSX files using the 'prettier' algorithm. Works for EcmaScript 6+";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "JavaScript, JSX, EcmaScript, formatting";
    }
}
