// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JavaScriptPrettier
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPrettierPackageString = "9c23598a-3625-4542-8488-a3777c7dac01";
        public const string guidPrettierPackageCmdSetString = "1adbe5b8-de7d-446c-85d6-c1c121aacff3";
        public static Guid guidPrettierPackage = new Guid(guidPrettierPackageString);
        public static Guid guidPrettierPackageCmdSet = new Guid(guidPrettierPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int PrettierCommandId = 0x0100;
    }
}
